---
- hosts: "{{ hosts }}"
  tasks:
    - name: Create directory c:\ts_data\test
      win_file:
        path: c:\ts_data\test
        state: directory
      when: ansible_ip_addresses[0] == "192.168.17.202"
      
